[Interface]
Address = 172.30.20.2
PrivateKey = sBhYOAyADbwrVWkZZPiF1EKglgEIuICAcACbpQu1/FU=
ListenPort = 51820
DNS = 1.1.1.1

[Peer]
PublicKey = nowtPMiDuoiqI56pvaZs1Stp6KQzhDRlu9tsAC3ZjTw=
PresharedKey = fsVvClKl2lc7GPIbE46QLRdmy+uS3yNFuKbQphkl5ew=
Endpoint = :51820
AllowedIPs = 0.0.0.0/0, ::/0
