[Interface]
Address = 172.30.20.1
ListenPort = 51820
PrivateKey = kIiupbMYxh+LWW8qKlkT9F1LYUj1lCUfF38deTkRkWw=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE

[Peer]
# peer_alice
PublicKey = QpzUq4WNuDDKKlmgiEZeRb9ESuln2IJXzyYcYjtpoRw=
PresharedKey = fsVvClKl2lc7GPIbE46QLRdmy+uS3yNFuKbQphkl5ew=
AllowedIPs = 172.30.20.2/32

